version: "3.8"

services:
  deno:
    build:
      context: ./server
    networks:
      - backend
    ports:
      - "9000:9000"
      - "9443:443"

  # ===========================================================================================================================

networks:
  backend:
